
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: banking_v1
    open-in-view: false

  liquibase:
    change-log: classpath:db/migration/changelog-master.yml

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}